baseurl = "http://www.yourdomain.com/"
languageCode = "en-us"
title = "Universal"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10
theme = "universal"

[params]
    author = "DevCows"
    # bio = "Blogger - Programmer - Gopher"
    # location = "Earth"
    # site_description = ""
    copyright  = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."
    # avatar = "css/images/avatar.png"
    # Format dates with Go's time formatting
    date_format = "2006-01-02"
    logo = "images/logo.png"

[[params.menu]]
    name = "Home"
    url  = "/"
    weight = 1

[[params.menu]]
    name = "Blog"
    url  = "/post"
    weight = 2

[social]
    github = "devcows"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true

[[params.carousel]]
    title = "Multipurpose responsive theme"
    description = "<p>Business. Corporate. Agency.<br>Portfolio. Blog. E-commerce.</p>"
    image = "images/carousel/template-homepage.png"

[[params.carousel]]
    title = "46 HTML pages full of features"
    description = """<ul class="list-style-none">
                       <li>Sliders and carousels</li>
                       <li>4 Header variations</li>
                       <li>Google maps, Forms, Megamenu, CSS3 Animations and much more</li>
                       <li>+ 11 extra pages showing template features</li>
                     </ul>"""
    image = "images/carousel/template-mac.png"

[[params.carousel]]
    title = "Design"
    description = """<ul class="list-style-none">
                        <li>Clean and elegant design</li>
                        <li>Full width and boxed mode</li>
                        <li>Easily readable Roboto font and awesome icons</li>
                        <li>7 preprepared colour variations</li>
                     </ul>"""
    image = "images/carousel/template-easy-customize.png"

[[params.carousel]]
    title = "Easy to customize"
    description = """<ul class="list-style-none">
                        <li>7 preprepared colour variations.</li>
                        <li>Easily to change fonts</li>
                     </ul>"""
    image = "images/carousel/template-easy-code.png"

[[params.features]]
    name = "Webdesign"
    icon = "fa fa-desktop"
    description = "Fifth abundantly made Give sixth hath. Cattle creature i be don't them behold green moved fowl Moved life us beast good yielding. Have bring."

[[params.features]]
    name = "Print"
    icon = "fa fa-print"
    description = "Advantage old had otherwise sincerity dependent additions. It in adapted natural hastily is justice. Six draw you him full not mean evil. Prepare garrets it expense windows shewing do an."

[[params.testimonials]]
    text = "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections."
    name = "John McIntyre"
    position = "CEO, TransTech"
    avatar = "images/testimonials/person-1.jpg"

[[params.testimonials]]
    text = "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections."
    name = "John McIntyre"
    position = "CEO, TransTech"
    avatar = "images/testimonials/person-1.jpg"

[[params.testimonials]]
    text = "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections."
    name = "John McIntyre"
    position = "CEO, TransTech"
    avatar = "images/testimonials/person-1.jpg"

[[params.testimonials]]
    text = "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections."
    name = "John McIntyre"
    position = "CEO, TransTech"
    avatar = "images/testimonials/person-1.jpg"

[[params.testimonials]]
    text = "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections."
    name = "John McIntyre"
    position = "CEO, TransTech"
    avatar = "images/clients/person-1.jpg"

[[params.clients]]
    name = "customer-1"
    image = "images/clients/customer-1.png"

[[params.clients]]
    name = "customer-2"
    image = "images/clients/customer-2.png"

[[params.clients]]
    name = "customer-3"
    image = "images/clients/customer-3.png"

[[params.clients]]
    name = "customer-4"
    image = "images/clients/customer-4.png"

[[params.clients]]
    name = "customer-5"
    image = "images/clients/customer-5.png"

[[params.clients]]
    name = "customer-6"
    image = "images/clients/customer-6.png"
